language: node_js
node_js:
- "node"

cache: yarn

sudo: true

before_install:
  - gem install bundler
  - gem install danger

before_script:
- npm install -g yarn

script:
- make test

after_sucess:
- danger
